"""empty message

Revision ID: 246538276fe4
Revises: f480509ca4fb
Create Date: 2022-05-19 12:59:09.471452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246538276fe4'
down_revision = 'f480509ca4fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'name')
    # ### end Alembic commands ###
