"""empty message

Revision ID: 3d3c58eecc3d
Revises: 8bab249d35b5
Create Date: 2022-05-22 17:59:35.124797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3c58eecc3d'
down_revision = '8bab249d35b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.add_column('Shows', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'past_shows_count')
    op.drop_column('Shows', 'upcoming_shows_count')
    # ### end Alembic commands ###
