"""empty message

Revision ID: 3e66229fca33
Revises: b0c170cb6a2f
Create Date: 2022-05-19 12:22:34.870443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e66229fca33'
down_revision = 'b0c170cb6a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('website', sa.String(length=200), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=300), nullable=True))
    op.add_column('Artist', sa.Column('available', sa.Boolean(), nullable=True))
    op.add_column('Shows', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('Shows', sa.Column('start_time', sa.Date(), nullable=False))
    op.add_column('Shows', sa.Column('upcoming_shows', sa.Boolean(), nullable=True))
    op.add_column('Shows', sa.Column('past_shows', sa.Boolean(), nullable=True))
    op.add_column('Shows', sa.Column('Venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Shows', 'Venue', ['Venue_id'], ['id'])
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=200), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.drop_column('Shows', 'Venue_id')
    op.drop_column('Shows', 'past_shows')
    op.drop_column('Shows', 'upcoming_shows')
    op.drop_column('Shows', 'start_time')
    op.drop_column('Shows', 'date')
    op.drop_column('Artist', 'available')
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
