"""empty message

Revision ID: 63f3e3bd4a4a
Revises: f1ef34f00133
Create Date: 2022-05-19 23:46:36.703451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f3e3bd4a4a'
down_revision = 'f1ef34f00133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.String(length=120), nullable=True))
    op.alter_column('Artist', 'available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.alter_column('Artist', 'available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
