"""empty message

Revision ID: cf79b8402a29
Revises: bfdfd3697b8a
Create Date: 2022-05-19 13:35:33.594582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf79b8402a29'
down_revision = 'bfdfd3697b8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('Shows', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.drop_constraint('Shows_Artist_id_fkey', 'Shows', type_='foreignkey')
    op.drop_constraint('Shows_Venue_id_fkey', 'Shows', type_='foreignkey')
    op.create_foreign_key(None, 'Shows', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'Shows', 'Artist', ['artist_id'], ['id'])
    op.drop_column('Shows', 'Artist_id')
    op.drop_column('Shows', 'Venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('Venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Shows', sa.Column('Artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.create_foreign_key('Shows_Venue_id_fkey', 'Shows', 'Venue', ['Venue_id'], ['id'])
    op.create_foreign_key('Shows_Artist_id_fkey', 'Shows', 'Artist', ['Artist_id'], ['id'])
    op.drop_column('Shows', 'venue_id')
    op.drop_column('Shows', 'artist_id')
    # ### end Alembic commands ###
